name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read  # minimum needed to checkout code, fetch dependencies, etc.
  # OPTIONAL elevated writes — uncomment ONLY if the job truly needs them (principle of least privilege):
  # pull-requests: write  # e.g., annotate PRs, post review comments, update labels
  # issues: write         # e.g., create/update issues


jobs:
  lint_typecheck_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
