name: Register Discord Commands

on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Where to register commands"
        required: true
        default: "guild"
        type: choice
        options:
          - guild
          - global

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Register commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: |
          set -euo pipefail
          SCOPE="${{ github.event.inputs.scope }}"
          echo "Registering commands for scope: ${SCOPE}"
          if [ "${SCOPE}" = "global" ]; then
            pnpm run register:global
          else
            pnpm run register:guild
          fi
